### PR TITLE
Added Bender.yml file

### PR DESCRIPTION
**Pull request by micprog**

### CODE REVIEW

**Review by andreaskurth — COMMENTED** [review]
The files listed under `sources` look good to me.

How did you derive the dependencies along with their versions, since there is no `ips_list.yml` in this repository?

`authors` should list `Igor Loi <igor.loi@unibo.it>`.

And finally a nit: please add the missing newline at EOF.

**Comment by micprog** [comment]
Dependencies were derived by checking each file for its included modules, while versions were taken from the ones originally imported by dependencies in the [pulp](https://github.com/pulp-platform/pulp) repository, or its dependencies ([pulp_soc](https://github.com/pulp-platform/pulp_soc)).

**Comment by andreaskurth** [comment]
> Dependencies were derived by checking each file for its included modules, while versions were taken from the ones originally imported by dependencies in the [pulp](https://github.com/pulp-platform/pulp) repository, or its dependencies ([pulp_soc](https://github.com/pulp-platform/pulp_soc)).

Great, thanks! LGTM now.

**Review by andreaskurth — APPROVED** [review]

**Comment by andreaskurth** [comment]
@igorloi Please review and, if you approve, merge this PR.

**Pull request merged**
